########################################################################################################################
#                                                                                                                      #
#                                          Wallet Configuration Options                                                #
#                                                                                                                      #
########################################################################################################################

[wallet]
# Override common.network for wallet
override_from = "dibbler"

# The relative folder to store your local key data and transaction history. DO NOT EVER DELETE THIS FILE unless you
#  a) have backed up your seed phrase and
#  b) know what you are doing!
db_file = "wallet/wallet.dat"

# The socket to expose for the gRPC wallet server. This value is ignored if grpc_enabled is false.
grpc_address = "/ip4/127.0.0.1/tcp/18143"

# Console wallet password
# Should you wish to start your console wallet without typing in your password, the following options are available:
# 1. Start the console wallet with the --password=secret argument, or
# 2. Set the environment variable TARI_WALLET_PASSWORD=secret before starting the console wallet, or
# 3. Set the "password" key in this [wallet] section of the config
# password = "secret"

# WalletNotify
# Allows you to execute a script or program when these transaction events are received by the console wallet:
# - transaction received
# - transaction sent
# - transaction cancelled
# - transaction mined but unconfirmed
# - transaction mined and confirmed
# An example script is available here: applications/tari_console_wallet/src/notifier/notify_example.sh
# notify = "/path/to/script"

# This is the timeout period that will be used to monitor TXO queries to the base node (default = 60). Larger values
# are needed for wallets with many (>1000) TXOs to be validated.
#base_node_query_timeout = 180
# The amount of seconds added to the current time (Utc) which will then be used to check if the message has
# expired or not when processing the message (default = 10800).
#saf_expiry_duration = 10800
# This is the number of block confirmations required for a transaction to be considered completely mined and
# confirmed. (default = 3)
#transaction_num_confirmations_required = 3
# This is the timeout period that will be used for base node broadcast monitoring tasks (default = 60)
#transaction_broadcast_monitoring_timeout = 180
# This is the timeout period that will be used for chain monitoring tasks (default = 60)
#transaction_chain_monitoring_timeout = 60
# This is the timeout period that will be used for sending transactions directly (default = 20)
#transaction_direct_send_timeout = 180
# This is the timeout period that will be used for sending transactions via broadcast mode (default = 60)
#transaction_broadcast_send_timeout = 180
# This is the size of the event channel used to communicate transaction status events to the wallet's UI. A busy console
# wallet doing thousands of bulk payments or used for stress testing needs a fairly big size (>10000) (default = 1000).
#transaction_event_channel_size = 25000
# This is the size of the event channel used to communicate base node events to the wallet. A busy console
# wallet doing thousands of bulk payments or used for stress testing needs a fairly big size (>3000) (default = 250).
#base_node_event_channel_size = 3500
# This is the size of the event channel used to communicate output manager events to the wallet. A busy console
# wallet doing thousands of bulk payments or used for stress testing needs a fairly big size (>3000) (default = 250).
#output_manager_event_channel_size = 3500
# This is the size of the event channel used to communicate base node update events to the wallet. A busy console
# wallet doing thousands of bulk payments or used for stress testing needs a fairly big size (>300) (default = 50).
#base_node_update_publisher_channel_size = 500
# If a large amount of tiny valued uT UTXOs are used as inputs to a transaction, the fee may be larger than
# the transaction amount. Set this value to `false` to allow spending of "dust" UTXOs for small valued
# transactions (default = true).
#prevent_fee_gt_amount = false
# This option specifies the transaction routing mechanism as being directly between wallets, making
# use of store and forward or using any combination of these.
# (options: "DirectOnly", "StoreAndForwardOnly", DirectAndStoreAndForward". default: "DirectAndStoreAndForward").
#transaction_routing_mechanism = "DirectAndStoreAndForward"

# When running the console wallet in command mode, use these values to determine what "stage" and timeout to wait
# for sent transactions.
# The stages are:
# - "DirectSendOrSaf" - The transaction was initiated and was accepted via Direct Send or Store And Forward.
# - "Negotiated" - The recipient replied and the transaction was negotiated.
# - "Broadcast" - The transaction was broadcast to the base node mempool.
# - "MinedUnconfirmed" - The transaction was successfully detected as mined but unconfirmed on the blockchain.
# - "Mined" - The transaction was successfully detected as mined and confirmed on the blockchain.

# The default values are: "Broadcast", 300
#command_send_wait_stage = "Broadcast"
#command_send_wait_timeout = 300

# The base nodes that the wallet should use for service requests and tracking chain state.
# base_node_service_peers = ["public_key::net_address", ...]
# base_node_service_peers = ["e856839057aac496b9e25f10821116d02b58f20129e9b9ba681b830568e47c4d::/onion3/exe2zgehnw3tvrbef3ep6taiacr6sdyeb54be2s25fpru357r4skhtad:18141"]

# Configuration for the wallet's base node service
# The refresh interval, defaults to 10 seconds
#base_node_service_refresh_interval = 30
# The maximum age of service requests in seconds, requests older than this are discarded
#base_node_service_request_max_age = 180

#[base_node.transport.tor]
#control_address = "/ip4/127.0.0.1/tcp/9051"
#control_auth_type = "none" # or "password"
# Required for control_auth_type = "password"
#control_auth_password = "super-secure-password"

[wallet.p2p]

[wallet.p2p.transport]
# # Configures the node to run over a tor hidden service using the Tor proxy. This transport recognises ip/tcp,
# # onion v2, onion v3 and dns addresses.
type = "tor"
# Address of the tor control server
tor_control_address = "/ip4/127.0.0.1/tcp/9051"
# The address to which traffic on the node's onion address will be forwarded
tor_forward_address = "/ip4/127.0.0.1/tcp/0"
# Authentication to use for the tor control server
tor_control_auth = "none" # or "password=xxxxxx"
# The onion port to use.
tor_onion_port = 18141
# When these peer addresses are encountered when dialing another peer, the tor proxy is bypassed and the connection is made
# directly over TCP. /ip4, /ip6, /dns, /dns4 and /dns6 are supported.
tor_proxy_bypass_addresses = []
# When using the tor transport and set to true, outbound TCP connections bypass the tor proxy. Defaults to false for better privacy
tor_proxy_bypass_for_outbound_tcp = false

[dibbler.wallet]
network = "dibbler"

[dibbler.wallet.p2p]
dns_seeds = ["seeds.dibbler.tari.com"]
peer_seeds = [
    # 333388d1cbe3e2bd17453d052f
    "c2eca9cf32261a1343e21ed718e79f25bfc74386e9305350b06f62047f519347::/onion3/6yxqk2ybo43u73ukfhyc42qn25echn4zegjpod2ccxzr2jd5atipwzqd:18141",
    # 555575715a49fc242d756e52ca
    "42fcde82b44af1de95a505d858cb31a422c56c4ac4747fbf3da47d648d4fc346::/onion3/2l3e7ysmihc23zybapdrsbcfg6omtjtfkvwj65dstnfxkwtai2fawtyd:18141",
    # 77771f53be07fab4be5f1e1ff7
    "50e6aa8f6c50f1b9d9b3d438dfd2a29cfe1f3e3a650bd9e6b1e10f96b6c38f4d::/onion3/7s6y3cz5bnewlj5ypm7sekhgvqjyrq4bpaj5dyvvo7vxydj7hsmyf5ad:18141",
    # 9999016f1f3a6162dddf5a45aa
    "36a9df45e1423b5315ffa7a91521924210c8e1d1537ad0968450f20f21e5200d::/onion3/v24qfheti2rztlwzgk6v4kdbes3ra7mo3i2fobacqkbfrk656e3uvnid:18141",
    # bbbb8358387d81c388fadb4649
    "be128d570e8ec7b15c101ee1a56d6c56dd7d109199f0bd02f182b71142b8675f::/onion3/ha422qsy743ayblgolui5pg226u42wfcklhc5p7nbhiytlsp4ir2syqd:18141",
    # eeeeb0a943ed143e613a135392
    "3e0321c0928ca559ab3c0a396272dfaea705efce88440611a38ff3898b097217::/onion3/sl5ledjoaisst6d4fh7kde746dwweuge4m4mf5nkzdhmy57uwgtb7qqd:18141"
]

