[package]
name = "tari_console_wallet"
version = "0.5.0"
authors = ["Philip Robinson <simian@tari.com>"]
edition = "2018"

[dependencies]
tari_wallet = { version = "^0.2", path = "../../base_layer/wallet" }
tari_crypto = { version = "^0.5" }
tari_common = { version= "^0.2", path = "../../common" }
tari_app_utilities = { version = "^0.1.0", path = "../tari_app_utilities"}
tari_comms = { version = "^0.2", path = "../../comms"}
tari_comms_dht = { version = "^0.2", path = "../../comms/dht"}
tari_p2p = { version= "^0.2", path = "../../base_layer/p2p" }
tari_app_grpc = {  path = "../tari_app_grpc" }

chrono = { version = "0.4.6", features = ["serde"]}
crossterm = { version = "0.17"}
rand = "0.7.2"
unicode-width = "0.1"
lazy_static = "1.4.0"
unicode-segmentation = "1.6.0"
log = { version = "0.4.8", features = ["std"] }
structopt = { version = "0.3.13", default_features = false }
config = { version = "0.9.3" }
qrcode = { version = "0.12" }
dirs = "2.0.2"
tokio = { version="0.2.10", features = ["signal"] }
thiserror = "1.0.20"
tonic = "0.2"

[dependencies.tari_core]
path = "../../base_layer/core"
version = "^0.2"
default-features = false
features = ["transactions", "mempool_proto", "base_node_proto"]

[dependencies.tui]
version = "0.10"
default-features = false
features = ["crossterm"]
