[package]
name = "tari_app_utilities"
version = "0.1.0"
authors = ["Philip Robinson <simian@tari.com>"]
edition = "2018"

[dependencies]
tari_comms = { version = "^0.2", path = "../../comms"}
tari_crypto = { version = "^0.5" }
tari_common = { version= "^0.2", path = "../../common" }
tari_p2p = { version= "^0.2", path = "../../base_layer/p2p" }

qrcode = { version = "0.12" }
dirs = "2.0.2"
serde_json = "1.0"
log = { version = "0.4.8", features = ["std"] }
rand = "0.7.2"
tokio = { version="0.2.10", features = ["signal"] }

[dependencies.tari_core]
path = "../../base_layer/core"
version = "^0.2"
default-features = false
features = ["transactions"]