[package]
name = "tari_hashing"
version = "1.0.0-dan.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_crypto = "0.20.0"
digest = "0.10"
borsh = "1.2"

[dev-dependencies]
blake2 = "0.10"