[book]
authors = ["Philip Robinson", "Byron Hambly"]
language = "en"
multilingual = false
src = "src"
title = "Tari Protocol Developer Documentation"

[output.html]
mathjax-support=true
theme = "src/theme"