on:
  push:
    branches:
      - development

name: Version

jobs:
  bump:
    name: patch crate versions
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.TARI_DEPLOY_SECRET_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false
      - name: install
        run: |
          echo "This is a lot faster than building from source ⚡"
          curl -o /tmp/cargo-workspaces -L https://github.com/tari-project/cargo-workspaces/releases/download/v0.2.24/cargo-workspaces-v0.2.24-x86_64-linux-gnu
          HASH=$(shasum /tmp/cargo-workspaces)
          EXPECTED="94901503e751564153392c8f93bfebdc349e650c  /tmp/cargo-workspaces"
          if [ "$HASH" != "$EXPECTED" ]; then
            echo "Well, this is awkward.";
            echo "The hash of the downloaded binary doesn't match what's expected.";
            echo "Either the binary has been innocently changed without updating the expected hash,"
            echo "or it's compromised and you're under attack!"
            echo "Bailing out."
            exit 1
          fi
          chmod +x /tmp/cargo-workspaces
      - name: git config
        run: |
          git config --global user.name "tari-deploy"
          git config --global user.email "bug_reports@tari.com"
      - name: crates list
        run: |
          pwd
          /tmp/cargo-workspaces workspaces list
      - name: bump patch version
        run: |
          /tmp/cargo-workspaces workspaces version patch \
          --no-git-tag \
          --sign-commit \
          --no-global-tag \
          --force "*" \
          -y \
          -m "ci: bump crate versions to %v [skip ci]" \
          --allow-branch development
